config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :new, :create, :show]
  
  resources :sessions, only: [:new, :create, :destroy]

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :password_digest, presence: true
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}
  
  attr_reader :password

  after_initialize :ensure_session_token  
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end
  
  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
  
  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(value)
    @password = value
    self.password_digest = BCrypt::Password.create(@password)
  end
  
  def is_password?(value)
    BCrypt::Password.new(self.password_digest).is_password?(value)
  end

  def self.find_by_credentials(email, password)  
    user = User.find_by(email: email)
    return nil if user.nil?
    return user if user.is_password?(password)
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  # protect_from_forgery with: :exception
  
  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end
  
  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end
  
  def logged_in?
    return true if session[:session_token]
  end
  
  def log_out!
    return nil unless logged_in?
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  helper_method :current_user
  def new
    render :new
  end
  
  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if user
      log_in_user!(user)
      redirect_to users_url
    else
      flash[:errors] = ['Wrong username/password combination']
      render :new
    end
  end
  
  def destroy
    log_out!
    redirect_to users_url
  end
  
end

#Write controller methods and the accompanying routes so that users can log in and log out. Should session be a singular resource?
#Controller#create should re-set the appropriate user's session_token and session[:session_token].
#For now just redirect them to a User#show page which simply displays that user's email.

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index 
    @user = User.new
    render :index
  end
  
  def show
    @user = User.find_by(id: params[:id])
    render :show
  end
  
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.new(user_params)
    # @user.password = params[:password]
    if @user.save
      redirect_to users_url
    else
      flash[:errors] = ['Email/Password combination did not create a new user']
      redirect_to new_user
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:email, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    
    <% if self.controller.logged_in? %>
      <h4>Hello <%= current_user.email %>!</h4>
      <%= button_to "Sign Out", session_url(current_user), method: "delete"  %>
    <% else  %>
    <nav>
      <%= link_to "Log In", new_session_url%>
      <%= link_to "Sign Up", new_user_url%>
    </nav>
    <% end %>   
    <h1>Welcome to the Music App</h1>
 
  </header>

    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1>Below are all of MusicApp's users </h1>

<% User.all.each do |user| %>
  <ul>
    <li><%= user.email %></li>
    <li><%= user.session_token %></li>
    <li><%= user.password_digest %></li>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up Today!!</h1>

<form action="<%= users_url %>" method="POST">
  <label for="email_box">Email:</label>
  <input 
    id="email_box" 
    type="text" 
    name="user[email]" >
    
  <label for="password_box">Password: </label>
  <input 
    id="password_box" 
    type="password" 
    name="user[password]" >
    
  <input type="submit" value="Submit">
</form>

app/views/users/show.html.erb
<ul>
  <li><%= @user.email %></li>
  <li><%= @user.password_digest %></li>
  <li><%= @user.session_token %></li>

</ul>